spring:
  profiles:
    active: dev
    include: swagger
  liquibase:
    contexts: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  jackson:
    serialization.indent_output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/fingermatchingdb
    username: fg_matching_user
    password: fg_matching_pwd
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  thymeleaf:
    cache: false
server:
  port: 8084
jhipster:
  http:
    version: V_1_1
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 100
  cors:
    allowed-origins: '*'
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    allowed-headers: '*'
    exposed-headers: null
    allow-credentials: true
    max-age: 1800
  metrics:
    jmx.enabled: true
    graphite:
      enabled: false
      host: localhost
      port: 2003
      prefix: fingermatching
    prometheus:
      enabled: false
      endpoint: /prometheusMetrics
    logs:
      enabled: false
      report-frequency: 60
  logging:
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
application: null