version: '2'
services:
  fg_matching_api_app:
    image: fg_matching_api
    environment:
    - SPRING_PROFILES_ACTIVE=prod,swagger
    - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-3-90-168-153.compute-1.amazonaws.com:9111/fingermatchingdb
    - JHIPSTER_SLEEP=10
    ports:
    - 8084:8084
  fg_matching_postgresql:
    extends:
      file: postgresql.yml
      service: fg_matching_postgresql